# 使用串列與元組建立一維陣列

In [4]:
import numpy as np

In [15]:
ls_a = [1, 2, 3, 4, 5]
a = np.array(ls_a) 
tp_b = (1, 2, 3, 4, 5)
b = np.array(tp_b) 

In [17]:
a

array([1, 2, 3, 4, 5])

In [19]:
type(a)

numpy.ndarray

In [21]:
a[0]

1

In [23]:
a[2] = 10


In [25]:
a

array([ 1,  2, 10,  4,  5])

# 使用使用串列建立二維陣列

In [12]:
ls_a = [[1,2,3],[4,5,6]]
a = np.array(ls_a)


In [22]:
a[1, 2] # numpy indexing

6

In [24]:
a[1][2] # numpy indexing

6

In [26]:
ls_a[1][2]

6

In [28]:
a.dtype

dtype('int32')

# 建立指定元素型態的陣列

In [78]:
a = np.array([1, 2, 3, 4, 5], int) 
b = np.array((1, 2, 3, 4, 5), dtype=float) 


# NumPy更多陣列建立函數

In [86]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [82]:
b = np.arange(1, 6, 2)
b

array([1, 3, 5])

In [36]:
c = np.zeros(2) 
c

array([0., 0.])

In [40]:
d = np.zeros((3,2)) 
d

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
e = np.zeros((3,2, 1)) 
e

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [44]:
f = np.zeros((3,2, 2, 3)) 
f

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [48]:
g = np.full(2, 7)
g

array([7, 7])

In [50]:
h = np.full((2,2), 7)
h

array([[7, 7],
       [7, 7]])

In [64]:
d = np.eye(6, 5)  
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [60]:
e = np.eye(3, k=-1)
e

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [66]:
f = np.random.rand(3)
f

array([0.06313611, 0.01680817, 0.30068841])

In [72]:
g = np.random.rand(3,3, 3)
g

array([[[0.11649159, 0.21178527, 0.81497153],
        [0.49493241, 0.73937294, 0.84706195],
        [0.68942486, 0.16057227, 0.55399967]],

       [[0.22730177, 0.94906527, 0.79094412],
        [0.19957107, 0.95582625, 0.04016599],
        [0.37720472, 0.99840497, 0.83880572]],

       [[0.9617237 , 0.49968249, 0.3866618 ],
        [0.2253963 , 0.84774814, 0.84290513],
        [0.29225584, 0.77813242, 0.14244573]]])

# 陣列維度的轉換

In [90]:
a = np.arange(16)
b = a.reshape((4, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
c = a.reshape((2, 8))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [102]:
d = c.reshape(4, 4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
c = np.reshape(a, (8, 2))
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [120]:
c.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
c.reshape((16, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
np.squeeze(c.reshape((16, 1)), 1)

# 顯示NumPy陣列的屬性

In [155]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
 

In [130]:
a.dtype

dtype('int32')

In [132]:
a.size

25

In [134]:
a.shape

(5, 5)

In [136]:
a.itemsize

4

In [138]:
a.ndim

2

In [140]:
a.nbytes

100

In [145]:
a = np.array([[1, 2], [3, 4], [5, 6]])
for ele in a:
    print(ele)


[1 2]
[3 4]
[5 6]


In [ ]:
for ele in a:
    for item in ele:
        print(str(item) + " ", end="")


In [153]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [159]:
a = np.arange(2, 11, 2)

In [161]:
a


array([ 2,  4,  6,  8, 10])

In [163]:
a / 2

array([1., 2., 3., 4., 5.])

In [165]:
a // 2

array([1, 2, 3, 4, 5], dtype=int32)

In [167]:
a % 2

array([0, 0, 0, 0, 0], dtype=int32)

In [169]:
a % 3

array([2, 1, 0, 2, 1], dtype=int32)

In [179]:
a = np.array([1, 2, 3]) 
s = np.array([4, 5, 6, 7])  

In [181]:
b = a + s       
b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
b = a - s       

In [175]:
b = a * s     
b

array([ 4, 10, 18])

In [177]:
b = a / s       
b

array([0.25, 0.4 , 0.5 ])

# 向量的點積運算

In [184]:
a = np.array([1, 2, 3]) 
a

array([1, 2, 3])

In [186]:
s = np.array([4, 5, 6])  
s

array([4, 5, 6])

In [188]:
b = a.dot(s)
b

32

In [190]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a[2:-2]
b

array([3, 4, 5, 6, 7])

# 矩陣相乘(dot product)

In [199]:
a = np.array([[1,2],[3,4]])
s = np.array([[5,6],[7,8]])

In [201]:
b = a.dot(s)
b

array([[19, 22],
       [43, 50]])

In [203]:
c = s.dot(a)
c

array([[23, 34],
       [31, 46]])

In [205]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [209]:
s = np.array([[5],[6]])
s

array([[5],
       [6]])

In [211]:
a.dot(s)

array([[17],
       [39]])

In [215]:
s.transpose().dot(a)

array([[23, 34]])

In [217]:
s

array([[5],
       [6]])

In [221]:
s.transpose()

array([[5, 6]])